/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Condition: { // root type
    aqi: number; // Int!
    coord: number[]; // [Float!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: {};
  Query: {};
  SafeUser: { // root type
    name: string; // String!
  }
  SignUp: { // root type
    condition: NexusGenRootTypes['Condition']; // Condition!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // root type
    coord: number[]; // [Float!]!
    email?: string | null; // String
    id: number; // Int!
    name: string; // String!
    phone?: number | null; // Int
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Condition: { // field return type
    aqi: number; // Int!
    coord: number[]; // [Float!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: { // field return type
    delete: NexusGenRootTypes['User']; // User!
    signup: NexusGenRootTypes['SignUp']; // SignUp!
  }
  Query: { // field return type
    condition: NexusGenRootTypes['Condition']; // Condition!
    users: NexusGenRootTypes['SafeUser'][]; // [SafeUser!]!
  }
  SafeUser: { // field return type
    name: string; // String!
  }
  SignUp: { // field return type
    condition: NexusGenRootTypes['Condition']; // Condition!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    coord: number[]; // [Float!]!
    email: string | null; // String
    id: number; // Int!
    name: string; // String!
    phone: number | null; // Int
  }
}

export interface NexusGenFieldTypeNames {
  Condition: { // field return type name
    aqi: 'Int'
    coord: 'Float'
    updatedAt: 'DateTime'
  }
  Mutation: { // field return type name
    delete: 'User'
    signup: 'SignUp'
  }
  Query: { // field return type name
    condition: 'Condition'
    users: 'SafeUser'
  }
  SafeUser: { // field return type name
    name: 'String'
  }
  SignUp: { // field return type name
    condition: 'Condition'
    user: 'User'
  }
  User: { // field return type name
    coord: 'Float'
    email: 'String'
    id: 'Int'
    name: 'String'
    phone: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    delete: { // args
      email?: string | null; // String
      name: string; // String!
      phone?: number | null; // Int
    }
    signup: { // args
      coord: number[]; // [Float!]!
      email?: string | null; // String
      name: string; // String!
      phone?: number | null; // Int
    }
  }
  Query: {
    condition: { // args
      coord: number[]; // [Float!]!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}